name: .NET Core Desktop
on:
  push:
    branches:
      - "main"
      - "dev"

jobs:
  build:
    name: "Build and test"
    runs-on: ubuntu-latest 
    env:
      Solution_Name: EzCache

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Nuget restore
    - name: Install nuget package
      run: dotnet restore $Solution_Name
      working-directory: ./src

    # Build Solution
    - name: Build solution
      run: dotnet build -c Release
      working-directory: ./src
      

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test
      working-directory: ./src